### ISSUE TITLE
Can't Initialize a project with 1.7.0 image

### ISSUE THREAD

**Issue by PiWiBardy** [waldekmastykarz/docker-spfx#19] opened 2018-11-13 10:08 UTC
Hi,

I'm facing an error while initializing a project with yeoman in the 1.7.0 image.

i'm getting the following error 

====================================================

node-sass@4.9.3 install /usr/app/spfx/node_modules/node-sass
node scripts/install.js

fs.js:646
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EINVAL: invalid argument, open '/usr/app/spfx/node_modules/node-sass/package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.Module._extensions..json (module.js:670:20)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/app/spfx/node_modules/node-sass/lib/extensions.js:7:9)
    at Module._compile (module.js:653:30)

=========================================================

i tried with the 1.6 and the 1.5.1 image and it works fine.

thanks to find below the choice done during the yo man wizard

[https://pbs.twimg.com/media/DrvDtx4WsAAZadq.jpg](https://pbs.twimg.com/media/DrvDtx4WsAAZadq.jpg)

Regards,

**Comment by Concisive** [comment] 2018-11-13 14:30
I have just encountered the same issue on Docker for Windows. I created my own image based on the latest 1.7.0 dockerfile but I downgraded the version of node to 8.9.4. The first line of my dockerfile reads:

FROM node:8.9.4

The rest of the file is the same.

This change appears to work but I have not had time to test it extensively.

**Comment by PiWiBardy** [comment] 2018-11-15 10:13
it's maybe related to this issue : https://github.com/sass/node-sass/issues/2520

**Comment by waldekmastykarz** [comment] 2018-11-15 18:30
Thanks for looking into it. Let's see if the suggestion from the issue you mentioned would help to fix the issue on Windows

**Comment by JonasBjerke89** [comment] 2018-12-13 11:37
Any news on this matter?

**Comment by waldekmastykarz** [comment] 2018-12-13 18:41
Unfortunately, not yet. Thanks for checking in though. I've been busy with other things lately and didn't have the time to look into this yet.

**Comment by YannickRe** [comment] 2018-12-21 14:56
Same issue here, it worked using yarn instead of npm.

**Comment by waldekmastykarz** [comment] 2019-01-13 20:50
As @YannickRe mentioned, installing packages works using yarn (`yo @microsoft/sharepoint --package-manager yarn`). When trying to use npm, I'm getting the reported error and when I try to mount node_modules as a volume, I'm getting checksum errors on typescript and other packages. So seems like using package managers other than npm is the way to go, at least now.

**Comment by shurick81** [comment] 2022-01-05 18:19
Hi, I tested it with different versions:

1.  1.7.0

```
md spfx170testwp00
cd spfx170testwp00
docker run --rm -v ${pwd}:/usr/app/spfx waldekm/spfx:1.7.0 yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
```

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/spfx/.npm/_logs/2022-01-05T17_29_16_770Z-debug.log
```

2.  1.7.1

```
md spfx171testwp00
cd spfx171testwp00
docker run --rm -v ${pwd}:/usr/app/spfx waldekm/spfx:1.7.1 yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
```

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/spfx/.npm/_logs/2022-01-05T17_36_52_961Z-debug.lo
```

3.  1.8.0

```
md spfx180testwp00
cd spfx180testwp00
docker run --rm -v ${pwd}:/usr/app/spfx waldekm/spfx:1.8.0 yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
```

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/spfx/.npm/_logs/2022-01-05T17_42_50_878Z-debug.log
```

4.  1.8.1

```
md spfx181testwp00
cd spfx181testwp00
docker run --rm -v ${pwd}:/usr/app/spfx waldekm/spfx:1.8.1 yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
```

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/spfx/.npm/_logs/2022-01-05T17_48_36_280Z-debug.log
```

5.  1.8.2

```
md spfx182testwp00
cd spfx182testwp00
docker run --rm -v ${pwd}:/usr/app/spfx waldekm/spfx:1.8.2 yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
```

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

6.  1.9.1

```
md spfx191testwp00
cd spfx191testwp00
docker run --rm -v ${pwd}:/usr/app/spfx waldekm/spfx:1.9.1 yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
```

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/spfx/.npm/_logs/2022-01-05T18_07_40_226Z-debug.log
```

7.  1.10.0

```
md spfx1100testwp00
cd spfx1100testwp00
docker run --rm -v ${pwd}:/usr/app/spfx waldekm/spfx:1.10.0 yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
```

No issues.

8.  1.11.0

```
md spfx1110testwp00
cd spfx1110testwp00
docker run --rm -v ${pwd}:/usr/app/spfx waldekm/spfx:1.11.0 yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
```

No issues.

So should we conclude that in v1.10.0 and further this issue is solved and we need to close this issue?

**Comment by waldekmastykarz** [comment] 2022-01-07 09:52
Thank you for running the tests @shurick81. The issue is with v1.7.0 and I don't think we can require folks to upgrade to a newer version of SPFx. If we can confirm that v1.7.0 works by itself but breaks in the image, then we should investigate it more closely.

**Comment by shurick81** [comment] 2022-01-07 12:35
So the test would be to install, say SPFx v1.7.0, in a normal operating system, not container and test `npm install`?

**Comment by waldekmastykarz** [comment] 2022-01-09 14:50
Correct. If that's working fine, but it's breaking in the Docker image, then we have a bug we need to fix. If both fail, then we can close this issue as an issue outside of our scope and perhaps let the SPFx engineering team know about it.

**Comment by shurick81** [comment] 2022-01-10 13:29
I extracted the versions from the old docker image:

```
docker run --rm waldekm/spfx:1.7.0 nodejs --version
v8.12.0
docker run --rm waldekm/spfx:1.7.0 gulp --version
[11:18:38] CLI version 3.9.1
docker run --rm waldekm/spfx:1.7.0 yo --version
2.0.5
```

Here's what I did on an empty Windows Server 2022 Azure VM then:

```Powershell
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install nodejs --version=8.12.0 -y
```

close console, then open a new one, run:

```Powershell
npm install gulp@3.9.1 yo@2.0.5 @microsoft/generator-sharepoint@1.7.0 --global
md c:\projects\spfx170testwp00
cd c:\projects\spfx170testwp00
yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
```

Output looks good: https://gist.github.com/shurick81/c4c21bd6ce6bea9a874d85f03270fb6a#file-nodejs-version-8-12-0-gulp-3-9-1-yo-2-0-5-microsoft-generator-sharepoint-1-7-0-output


Also tried with the newest nodejs 8:

```Powershell
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install nodejs --version=8.17.0 -y
```

close console, then open a new one, run:

```Powershell
npm install gulp@3.9.1 yo@2.0.5 @microsoft/generator-sharepoint@1.7.0 --global
md c:\projects\spfx170testwp00
cd c:\projects\spfx170testwp00
yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
```

Output looks good: https://gist.github.com/shurick81/c4c21bd6ce6bea9a874d85f03270fb6a#file-gulp-3-9-1-yo-2-0-5-microsoft-generator-sharepoint-1-7-0-output

Tried to build a new image with 1.7.0: https://github.com/waldekmastykarz/docker-spfx/blob/5f550f38e96effb7b9dae1d6b591f58130aff895/Dockerfile

```
docker build -t spfx:00 .
cd ..
md spfx170testwp00
cd spfx170testwp00
docker run --rm -v ${pwd}:/usr/app/spfx spfx:00 yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
```

Got some strange output:

```
docker run --rm -v ${pwd}:/usr/app/spfx spfx:00 yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:533
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/router.js:8:27)
```


Altered docker file, package versions:

```
FROM node:8.12.0

EXPOSE 5432 4321 35729

RUN npm i gulp@3.9.1 yo@2.0.5 @microsoft/generator-sharepoint@1.7.0 --global

VOLUME /usr/app/spfx
WORKDIR /usr/app/spfx
RUN useradd --create-home --shell /bin/bash spfx && \
    usermod -aG sudo spfx && \
    chown -R spfx:spfx /usr/app/spfx

USER spfx

CMD /bin/bash
```

Output contains the node-sass@4.9.3 error: https://gist.github.com/shurick81/c4c21bd6ce6bea9a874d85f03270fb6a#file-docker-nodejs-version-8-12-0-gulp-3-9-1-yo-2-0-5-microsoft-generator-sharepoint-1-7-0-output


Altered docker file, yo version:

```
FROM node:8.12.0

EXPOSE 5432 4321 35729

RUN npm i gulp@3.9.1 yo @microsoft/generator-sharepoint@1.7.0 --global

VOLUME /usr/app/spfx
WORKDIR /usr/app/spfx
RUN useradd --create-home --shell /bin/bash spfx && \
    usermod -aG sudo spfx && \
    chown -R spfx:spfx /usr/app/spfx

USER spfx

CMD /bin/bash
```

Output looks strange again:

```
PS C:\projects\spfx170testwp01> docker run --rm -v ${pwd}:/usr/app/spfx spfx:02 yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:533
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/router.js:8:27)
```

Altered docker file, gulp version:

```
FROM node:8.12.0

EXPOSE 5432 4321 35729

RUN npm i gulp yo@2.0.5 @microsoft/generator-sharepoint@1.7.0 --global

VOLUME /usr/app/spfx
WORKDIR /usr/app/spfx
RUN useradd --create-home --shell /bin/bash spfx && \
    usermod -aG sudo spfx && \
    chown -R spfx:spfx /usr/app/spfx

USER spfx

CMD /bin/bash
```

Output has the node-sass@4.9.3 error: https://gist.github.com/shurick81/c4c21bd6ce6bea9a874d85f03270fb6a#file-docker-nodejs-version-8-12-0-gulp-yo-2-0-5-microsoft-generator-sharepoint-1-7-0-output


Any thoughts?

**Comment by waldekmastykarz** [comment] 2022-01-10 15:42
Thank you for all the info @shurick81. Since the Docker image is based on Linux, do you have a way to try it on Linux? It could be that there are OS-specific issues that might behave correctly on Windows but break on Linux and in the Docker image.

**Comment by shurick81** [comment] 2022-01-10 16:17
The version of npm in the image above is 6.13.4,
while the version of npm in the image waldekm/spfx:1.7.0 is 6.4.1

**Comment by shurick81** [comment] 2022-01-10 17:10
There seems some correlation between the npm version and the error:

| Node.js image | npm version | Result |
| ------------- | ------------- | ------ |
| 8.14.0 | 6.4.1 | Error |
| 8.15.0 | 6.4.1 | Error |
| 8.16.0 | 6.4.1 | Error |
| 8.16.2 | 6.4.1 | Error |
| 8.17.0 | 6.13.4 | OK |

**Comment by waldekmastykarz** [comment] 2022-01-12 08:51
So if we upgraded the Node version in the 1.7.0 image it should work just fine, correct?

**Comment by shurick81** [comment] 2022-01-12 09:13
I guess so, but is it possible to upgrade for a user of existing image?

**Comment by waldekmastykarz** [comment] 2022-01-12 11:53
I think so. On each release I'm upgrading the `latest` label to point to the latest image so changing the contents of `1.7.0` by analogy should be possible as well.

**Comment by waldekmastykarz** [comment] 2022-01-12 12:03
I've updated the v1.7.0 image following @shurick81 findings and the issue should be solved now. Thank you all for your help 👏

**Closed by waldekmastykarz** 2022-01-12 12:03 UTC
Labels: needs investigation

**Comment by waldekmastykarz** [comment] 2022-01-13 07:24
Awesome! Thank you for confirming!

> Have you also updated 1.7.1 1.8.0 1.8.1 1.8.2 and 1.9.1?

No, I haven't. I wasn't aware that we had this issue in there too. Do we?

**Comment by shurick81** [comment] 2022-01-13 08:38
Yes, these 5 images also fail, so could you upgrade nodejs?

| Image tag | Current Node.js v. | Current NPM v. | Upgrade Node.js |
| -- | -- | -- | -- |
| 1.7.1 | 8.12.0 | 6.4.1 | 8.17.0 |
| 1.8.0 | 8.12.0 | 6.4.1 | 8.17.0 |
| 1.8.1 | 8.12.0 | 6.4.1 | 8.17.0 |
| 1.8.2 | 10.15.3 | 6.4.1 | 10.24.1 |
| 1.9.1 | 10.15.3 | 6.4.1 | 10.24.1 |

**Comment by shurick81** [comment] 2022-01-13 09:31
For each change I took the code from corresponding commits in history and changed them as little as necessary for fixing the issue:

### 1.7.1

```
FROM node:8.17.0

EXPOSE 5432 4321 35729

RUN npm i -g gulp yo@2.0.5 @microsoft/generator-sharepoint@1.7.1

VOLUME /usr/app/spfx
WORKDIR /usr/app/spfx
RUN useradd --create-home --shell /bin/bash spfx && \
    usermod -aG sudo spfx && \
    chown -R spfx:spfx /usr/app/spfx

USER spfx

CMD /bin/bash
```

### 1.8.0

```
FROM node:8.17.0

EXPOSE 5432 4321 35729

RUN npm i -g gulp@3 yo@2.0.5 @microsoft/generator-sharepoint@1.8.0

VOLUME /usr/app/spfx
WORKDIR /usr/app/spfx
RUN useradd --create-home --shell /bin/bash spfx && \
    usermod -aG sudo spfx && \
    chown -R spfx:spfx /usr/app/spfx

USER spfx

CMD /bin/bash
```

### 1.8.1

```
FROM node:8.17.0

EXPOSE 5432 4321 35729

RUN npm i -g gulp@3 yo@2.0.5 @microsoft/generator-sharepoint@1.8.1

VOLUME /usr/app/spfx
WORKDIR /usr/app/spfx
RUN useradd --create-home --shell /bin/bash spfx && \
    usermod -aG sudo spfx && \
    chown -R spfx:spfx /usr/app/spfx

USER spfx

CMD /bin/bash
```

### 1.8.2

```
FROM node:10.15.3

EXPOSE 5432 4321 35729

RUN npm i -g gulp@3 yo @microsoft/generator-sharepoint@1.8.2

VOLUME /usr/app/spfx
WORKDIR /usr/app/spfx
RUN useradd --create-home --shell /bin/bash spfx && \
    usermod -aG sudo spfx && \
    chown -R spfx:spfx /usr/app/spfx

USER spfx

CMD /bin/bash
```

### 1.9.1

```
FROM node:10.24.1

EXPOSE 5432 4321 35729

RUN npm i -g gulp@3 yo@2.0.5 @microsoft/generator-sharepoint@1.9.1

VOLUME /usr/app/spfx
WORKDIR /usr/app/spfx
RUN useradd --create-home --shell /bin/bash spfx && \
    usermod -aG sudo spfx && \
    chown -R spfx:spfx /usr/app/spfx

USER spfx

CMD /bin/bash
```

I only changed lines 1 and 5 (yo@2.0.5) and I tested that this is the minimum change required.

**Comment by waldekmastykarz** [comment] 2022-01-13 13:37
I updated the images you mentioned and added patch commits to the history for reference

**Comment by shurick81** [comment] 2022-01-13 15:37
Strange, this still returns `v8.12.0`:

```
docker run --rm waldekm/spfx:1.8.1 node -v
```

Could be that I have made a typo somewhere in this conversation.

**Comment by shurick81** [comment] 2022-01-13 15:48
I tested all the other images and they work just fine now, installing modules smoothly. Just the one above is left...
Strange that in this commit there seems to be 8.17.0 FROM:
https://github.com/waldekmastykarz/docker-spfx/commit/d9bf48fd691c2cc517270a21427cd8c7cb853c0b#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557

**Comment by waldekmastykarz** [comment] 2022-01-14 08:02
I'm not sure I understand: looking at the data you shared, 1.8.1 required Node 8.17.0, no?

**Comment by waldekmastykarz** [comment] 2022-01-14 11:52
So for 1.8.1 we have two commits: the original which used Node@8.12 and a patch which is Node@8.17. When you run the container, which version of Node is in the container?

**Comment by shurick81** [comment] 2022-01-14 12:06
I run this:

```
docker image rm waldekm/spfx:1.8.1
docker run --rm waldekm/spfx:1.8.1 node -v
```

The output:

```
v8.12.0
```

**Comment by shurick81** [comment] 2022-01-14 13:19
Now I see the updated image with version 8.17.0 and I tested that the `node-sass` error has gone!

**Comment by waldekmastykarz** [comment] 2022-01-14 18:24
Awesome! Thank you for confirming 👏
